### ISSUE TITLE
会继续开发吗

### ISSUE THREAD

**Issue by chengkai2022** [wll8/mockm#10]
做的很赞，简化了不少啊，不知道能不能支持比较复杂的接口呢

**Comment by wll8** [comment]
在继续开发的，按计划 mockm 每个月都会[发布新版本](https://hongqiye.com/doc/mockm/dev/change_log.html)。目前在开发自动存储后端接口修改记录的功能。

理论上不存在说比较复杂的接口支持不了，因为 mockm 中的接口实现其实是一个完整的后端侧， [websocket](https://hongqiye.com/doc/mockm/use/example.html#%E5%A6%82%E4%BD%95%E5%88%9B%E5%BB%BA-websocket-%E6%8E%A5%E5%8F%A3) 甚至是连接数据库、 微信后端验权这些都没有问题的。

示例：
- [如何接入微信消息推送](https://hongqiye.com/doc/mockm/use/example.html#%E5%A6%82%E4%BD%95%E6%8E%A5%E5%85%A5%E5%BE%AE%E4%BF%A1%E6%B6%88%E6%81%AF%E6%8E%A8%E9%80%81)
