### ISSUE TITLE
作者还会继续维护吗，在修改mm.config.js时，可能没写完有语法错误，这时重新读取mm.config.js，导致运行中的服务报错终止运行

### ISSUE THREAD

**Issue by ubsshin** [wll8/mockm#59]
是否可能实现：如果读取的mm.config.js有错误，继续运行旧的mm.config.js，这样每次修改就不必重启了
如果很困难就算了，感谢作者

**Comment by wll8** [comment]
1. 还在维护。
2. 除了语法级的错误是不会导致崩溃的。
3. 如果是语法正确的修改，比如添加一个 api 函数， mockm 会自动重载的，无需手动重启。

如果语法级错误导致崩溃，运行旧的配置，可能会出现逻辑不一致性。

比如：新配置运行 a b 函数，运行到 b 时崩溃，然后运行旧配置。旧配置中的 a 函数可能在业务逻辑中与新配置是冲突的。那么这时候就不好排查问题。

**Comment by ubsshin** [comment]
确实，用旧配置不妥，那有无可能对语法错误捕获异常但不做处理，只在控制台报错不引发崩溃，让服务继续运行，可以使用默认mm.config.js配置，直到语法正确再次重载
我经常修改mm.config.js改到一半切换到别的窗口复制粘贴api路径，触发ide自动保存，此时mm.config.js可能有语法错误，引发崩溃，切换回ide就要重启mockm😂
我不知道自动重载的原理是怎样的，如果依赖第三方库不好改的话就算了

**Comment by wll8** [comment]
1. 如果要检测语法错误，有两种方式：预执行、编译。如果预执行的话会出现上面提到的执行逻辑不统一的问题。如果使用编译器比如 babel 这些去先编译下试试看有没有语法错误的话，就得为此功能引入一个编译库。
2. mm.config.js 文件有保存动作时就会触发重新加载的（也就是你的 ide 自动保存触发的），mockm 的重载原理就是有一个监听文件变更（保存）的动作，然后重新使用子进程运行服务，实现方式[在这里](https://github.com/wll8/mockm/blob/b8125c7f3310a745062ad3dbd15951de3b951a79/server/run.js#L104)。
3. 如果要缓解此问题有一些方法：一：关闭你的 ide 自动保存、二：或使用其他不自动保存的编辑器编辑该配置（尴尬）、三：或从 web-ui 上编辑接口、四：或把配置文件抽离一部分（比如 api.js）出去在其他文件中 require 到 mm.config.js 里，这时候你不管怎么改 api.js 都不会导致 mockm 重启（除非你手动重启，因为 mockm 默认仅监听 mm.config.js 本身）。

**Comment by ubsshin** [comment]
感谢解答，我切窗口前检查一下是可以尽量避免的，以后有机会我抽时间研究下，这个库我应该会一直用下去的

**Comment by wll8** [comment]
就冲这句话，连夜[补充了文档](https://github.com/wll8/mockm/commit/989fefd1ec2fe67c3d45dc0faec33123cbe22838)，主要是：

- [上传测试用例，可以查看每个选项的使用实例](https://www.hongqiye.com/doc/mockm/case/)
- [增加插件文档，用于定制化服务](https://www.hongqiye.com/doc/mockm/config/option.html#config-plugin)
